#define LOCATION_MAIN_TEXTURE 1
#define LOCATION_DEPTH_TEXTURE 2
#define LOCATION_DEPTH_CAM_FOV 10
#define LOCATION_DEPTH_CAM_NEAR_PLANE 11
#define LOCATION_DEPTH_CAM_FAR_PLANE 12
#define LOCATION_DEPTH_MAP_INV_MODEL_MAT 13
#define LOCATION_EYES_INV_VIEW_MAT 20
#define LOCATION_EYES_IPD 21